const assert=require('node:assert/strict');
const C=require('../dist/workbench-core.js');
const csv='title,authors,doi,abstract\r\n"A, study","Lee; Kim",https://doi.org/10.1/ABC,"Line one\nLine ""two"""\r\n';
const rows=C.parseImport(csv,'csv');
assert.equal(rows[0].title,'A, study');assert.equal(rows[0].abstract,'Line one\nLine "two"');assert.equal(rows[0].doi,'10.1/abc');
assert.throws(()=>C.parseImport('title\n"unfinished','csv'));
const bib=C.parseImport('@article{key, title={A {Nested} Study}, author="Lee and Kim", year={2025}, doi={10.1/test}}\n@book{next,title="Another title",year=2024}','bib');
assert.equal(bib.length,2);assert.equal(bib[0].title,'A Nested Study');assert.equal(bib[0].authors,'Lee; Kim');assert.equal(bib[1].year,'2024');
assert.throws(()=>C.parseImport('@article{x,title={bad}','bib'));
const ris=C.parseImport('TY  - JOUR\nTI  - A paper\nAU  - One\nAU  - Two\nPY  - 2024/01/01\nER  -\n','ris');
assert.equal(ris[0].authors,'One; Two');assert.equal(ris[0].year,'2024');
assert.throws(()=>C.parseImport('TY  - JOUR\nTI  - incomplete','ris'));
const plan=C.planImport(rows,[{...rows[0],title:'Different title'},{...rows[0],doi:'',title:'  A,   STUDY  '},{...rows[0],title:'New title',doi:'10.2/new'},{...rows[0],title:'',doi:''}]);
assert.deepEqual(plan.map(r=>Boolean(r.reason)),[true,true,false,true]);
const p={question:'Question',proposal:'',papers:[{id:'p'}],evidence:[{id:'e',paperId:'p'}]};const w=C.normalize(p);
w.claims.push({id:'c',text:'Claim',status:'Tentative',links:[{evidenceId:'e',relation:'challenges'}]});
C.validateWorkbench(p);assert(C.checks(p).some(x=>x.includes('challenging')));
w.claims[0].links[0].evidenceId='missing';assert.throws(()=>C.validateWorkbench(p));w.claims[0].links[0].evidenceId='e';
w.attachments=[{paperId:'p',name:'x.pdf',data:'data:text/html;base64,abcd'}];assert.throws(()=>C.validateWorkbench(p));delete w.attachments;
w.design.push({id:'d',objective:'Understand',measure:'',collection:'Interviews',analysis:'Thematic',rationale:''});
assert(C.checks(p).some(x=>x.includes('measure')));assert(C.checks(p).some(x=>x.includes('rationale')));
console.log('PASS: CSV/RIS/BibTeX parsing, duplicate planning, malformed imports, backup reference validation, attachment validation, and transparent design checks.');
